import { Event, EventStatus, EventType } from "../models/event";

export class EventData {
  static todayEvents : Event[] = [
    {
      name: 'Football Match',
      description: 'Inter-university football tournament semi-finals.',
      picture: 'https://www.fisu.net/app/uploads/2023/10/paulista_university1.jpg',
      startTime: '3:00 PM',
      endTime: '5:00 PM',
      date: '2024-12-29',
      room: 'University Stadium',
      capacity: 500,
      going: 300,
      interested: 100,
      declined: 50,
      status: EventStatus.Available,
      price: 5,
      type: EventType.Sports,
    },
    {
      name: 'Freshers Party',
      description: 'Welcoming all the freshers with music, dance, and games.',
      picture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTE7luLlquO6JGKRCKH8jvKJ3x8ic4gOS4jxg&s',
      startTime: '7:00 PM',
      endTime: '11:00 PM',
      date: '2024-12-29',
      room: 'Main Hall',
      capacity: 200,
      going: 150,
      interested: 30,
      declined: 20,
      status: EventStatus.Available,
      price: 10,
      type: EventType.Party,
    },
    {
      name: 'Tech Conference 2024',
      description: 'Discussing the future of AI and machine learning.',
      picture: 'https://example.com/tech_conference.jpg',
      startTime: '10:00 AM',
      endTime: '4:00 PM',
      date: '2024-12-29',
      room: 'Auditorium',
      capacity: 300,
      going: 250,
      interested: 30,
      declined: 20,
      status: EventStatus.Available,
      price: 15,
      type: EventType.Conference,
    },
    {
      name: 'Painting Workshop',
      description: 'Learn painting techniques from professionals.',
      picture: 'https://example.com/painting_workshop.jpg',
      startTime: '2:00 PM',
      endTime: '5:00 PM',
      date: '2024-12-29',
      room: 'Art Studio',
      capacity: 25,
      going: 20,
      interested: 3,
      declined: 2,
      status: EventStatus.Booked,
      price: 10,
      type: EventType.Workshop,
    },
    {
      name: 'Cultural Fest',
      description: 'Experience a blend of music, dance, and traditions.',
      picture: 'https://example.com/cultural_fest.jpg',
      startTime: '5:00 PM',
      endTime: '10:00 PM',
      date: '2024-12-29',
      room: 'Open Grounds',
      capacity: 1000,
      going: 800,
      interested: 150,
      declined: 50,
      status: EventStatus.Available,
      price: 0, // Free entry
      type: EventType.Cultural,
    },
    {
      name: 'Guest Lecture on Space Exploration',
      description: 'Hear from NASA scientists about the future of space exploration.',
      picture: 'https://example.com/guest_lecture.jpg',
      startTime: '3:00 PM',
      endTime: '4:30 PM',
      date: '2024-12-29',
      room: 'Lecture Hall 1',
      capacity: 100,
      going: 90,
      interested: 5,
      declined: 5,
      status: EventStatus.Available,
      price: 0, // Free entry
      type: EventType.Academic,
    },
  ];

  static thisWeekEvents = [
    {
      name: 'Football Match',
      description: 'Inter-university football tournament semi-finals.',
      picture: 'https://example.com/football_match.jpg',
      startTime: '3:00 PM',
      endTime: '5:00 PM',
      date: '2024-12-30',
      room: 'University Stadium',
      capacity: 500,
      going: 300,
      interested: 100,
      declined: 50,
      status: EventStatus.Available,
      price: 5,
      type: EventType.Sports,
    },
    {
      name: 'Tech Conference 2024',
      description: 'Discussing the future of AI and machine learning.',
      picture: 'https://example.com/tech_conference.jpg',
      startTime: '10:00 AM',
      endTime: '4:00 PM',
      date: '2024-12-31',
      room: 'Auditorium',
      capacity: 300,
      going: 250,
      interested: 30,
      declined: 20,
      status: EventStatus.Available,
      price: 15,
      type: EventType.Conference,
    },
    {
      name: 'Freshers Party',
      description: 'Welcoming all the freshers with music, dance, and games.',
      picture: 'https://example.com/freshers_party.jpg',
      startTime: '7:00 PM',
      endTime: '11:00 PM',
      date: '2024-12-30',
      room: 'Main Hall',
      capacity: 200,
      going: 150,
      interested: 30,
      declined: 20,
      status: EventStatus.Available,
      price: 10,
      type: EventType.Party,
    },
    {
      name: 'Cultural Fest',
      description: 'Experience a blend of music, dance, and traditions.',
      picture: 'https://example.com/cultural_fest.jpg',
      startTime: '5:00 PM',
      endTime: '10:00 PM',
      date: '2024-12-31',
      room: 'Open Grounds',
      capacity: 1000,
      going: 800,
      interested: 150,
      declined: 50,
      status: EventStatus.Available,
      price: 0, // Free entry
      type: EventType.Cultural,
    },
  ];

  static thisMonthEvents = [
    {
      name: 'Football Match',
      description: 'Inter-university football tournament semi-finals.',
      picture: 'https://example.com/football_match.jpg',
      startTime: '3:00 PM',
      endTime: '5:00 PM',
      date: '2024-12-30',
      room: 'University Stadium',
      capacity: 500,
      going: 300,
      interested: 100,
      declined: 50,
      status: EventStatus.Available,
      price: 5,
      type: EventType.Sports,
    },
    {
      name: 'Tech Conference 2024',
      description: 'Discussing the future of AI and machine learning.',
      picture: 'https://example.com/tech_conference.jpg',
      startTime: '10:00 AM',
      endTime: '4:00 PM',
      date: '2024-12-31',
      room: 'Auditorium',
      capacity: 300,
      going: 250,
      interested: 30,
      declined: 20,
      status: EventStatus.Available,
      price: 15,
      type: EventType.Conference,
    },
    {
      name: 'New Year Party',
      description: 'Celebrate the new year with music and dancing.',
      picture: 'https://example.com/new_year_party.jpg',
      startTime: '8:00 PM',
      endTime: '1:00 AM',
      date: '2024-12-31',
      room: 'Main Hall',
      capacity: 300,
      going: 200,
      interested: 50,
      declined: 10,
      status: EventStatus.Available,
      price: 20,
      type: EventType.Party,
    },
    {
      name: 'Workshop on Machine Learning',
      description: 'Learn the basics of machine learning and AI technologies.',
      picture: 'https://example.com/machine_learning_workshop.jpg',
      startTime: '9:00 AM',
      endTime: '4:00 PM',
      date: '2024-12-28',
      room: 'Computer Lab 1',
      capacity: 30,
      going: 25,
      interested: 10,
      declined: 5,
      status: EventStatus.Available,
      price: 25,
      type: EventType.Workshop,
    },
  ];
}
